// POST /webhooks/judgeme/:token — Judge.me product-review webhook.
//
// Setup (merchant):
//   1. In Royal Loyalty admin > Settings > Integrations, connect Judge.me
//      with their Judge.me shop token (the long string from Judge.me's
//      Integrations / API tab).
//   2. Copy the displayed webhook URL — it includes their shop token as
//      the path segment for auth.
//   3. In Judge.me admin > Customizations > Webhooks, add the URL with
//      event "review/create".
//
// Auth model: the token in the URL must match a connected Judge.me
// integration's `shopToken`. No HMAC needed — the token IS the secret
// (32+ chars, generated by Judge.me, unguessable). We don't trust the
// payload for shop identification; the URL token is authoritative.
//
// Award flow: payload must include `reviewer_email` and a review `id`.
// We find the matching Member by email + shop, then call awardForAction
// with oncePerKey="review-{reviewId}" so re-deliveries don't double-pay.
import type { ActionFunctionArgs } from "react-router";
import prisma from "../db.server";
import { awardForAction } from "../lib/loyalty.server";

interface JudgeMeReviewPayload {
  id?: number | string;
  rating?: number;
  reviewer_email?: string | null;
  reviewer_name?: string | null;
  product_external_id?: string | null;
}

export const action = async ({ request, params }: ActionFunctionArgs) => {
  if (request.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }
  const token = String(params.token ?? "").trim();
  if (token.length < 8) {
    return new Response("Bad token", { status: 401 });
  }

  // Look up which shop owns this token. Integration rows are stored with
  // config as JSON; we filter in app code because Prisma's JSON path
  // filtering varies by database engine.
  const candidates = await prisma.integration.findMany({
    where: { service: "judgeme" },
  });
  const integration = candidates.find((i) => {
    const cfg = i.config as { shopToken?: string } | null;
    return cfg?.shopToken === token;
  });
  if (!integration) {
    return new Response("Unknown token", { status: 401 });
  }

  const body = (await request.json().catch(() => ({}))) as JudgeMeReviewPayload;
  if (!body.reviewer_email || !body.id) {
    return new Response("Bad payload", { status: 400 });
  }
  // Optional rating gate — only award for 4+ star reviews so the program
  // isn't gamed by 1-star spam. Configurable later if needed.
  if (typeof body.rating === "number" && body.rating < 4) {
    return Response.json({ ok: true, outcome: "low_rating_skipped" });
  }

  const member = await prisma.member.findFirst({
    where: {
      shopId: integration.shopId,
      email: body.reviewer_email,
      redactedAt: null,
    },
    select: { id: true },
  });
  if (!member) {
    // Reviewer isn't a loyalty member — silently OK to keep Judge.me's
    // webhook delivery healthy.
    return Response.json({ ok: true, outcome: "no_member" });
  }

  const result = await awardForAction({
    shopId: integration.shopId,
    memberId: member.id,
    action: "review",
    oncePerKey: `review-${body.id}`,
  });
  return Response.json({ ok: true, outcome: result.outcome });
};
